# This file was automatically generated by SDx
set_param project.loadTopLevelOOCConstrs 1
set_param project.writeIntermediateCheckpoints 0
set_param bd.ForceAppCoreUpgrade 1
set_msg_config -id "Timing 38-282" -new_severity ERROR

# Params added by user
