# This file was automatically generated by SDx
set_property -name STEPS.INIT_DESIGN.TCL.POST -value [pwd]/scripts/_full_init_post.tcl -objects [get_runs impl_1]
set_property -name STEPS.INIT_DESIGN.TCL.PRE -value [pwd]/scripts/_full_init_pre.tcl -objects [get_runs impl_1]
set_property -name STEPS.OPT_DESIGN.TCL.POST -value [pwd]/scripts/_full_opt_post.tcl -objects [get_runs impl_1]
set_property -name STEPS.OPT_DESIGN.TCL.PRE -value [pwd]/scripts/_full_opt_pre.tcl -objects [get_runs impl_1]
set_property -name STEPS.PLACE_DESIGN.TCL.POST -value [pwd]/scripts/_full_place_post.tcl -objects [get_runs impl_1]
set_property -name STEPS.PLACE_DESIGN.TCL.PRE -value [pwd]/scripts/_full_place_pre.tcl -objects [get_runs impl_1]
set_property -name STEPS.ROUTE_DESIGN.TCL.POST -value [pwd]/scripts/_full_route_post.tcl -objects [get_runs impl_1]
