# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/timothyduke/workspace/SeniorDesign/Debug/_sds/p0/vivado/output/Arty_Z7_20_ooc_copy.xdc

# Block Designs: bd/Arty_Z7_20/Arty_Z7_20.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20 || ORIG_REF_NAME==Arty_Z7_20} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_0_0/Arty_Z7_20_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_gpio_0_0 || ORIG_REF_NAME==Arty_Z7_20_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_1_0/Arty_Z7_20_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_gpio_1_0 || ORIG_REF_NAME==Arty_Z7_20_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_2_0/Arty_Z7_20_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_gpio_2_0 || ORIG_REF_NAME==Arty_Z7_20_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_3_0/Arty_Z7_20_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_gpio_3_0 || ORIG_REF_NAME==Arty_Z7_20_axi_gpio_3_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_axi_iic_0_0/Arty_Z7_20_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_iic_0_0 || ORIG_REF_NAME==Arty_Z7_20_axi_iic_0_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_clk_wiz_0_0/Arty_Z7_20_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_clk_wiz_0_0 || ORIG_REF_NAME==Arty_Z7_20_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_0/Arty_Z7_20_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_proc_sys_reset_0_0 || ORIG_REF_NAME==Arty_Z7_20_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_1_0/Arty_Z7_20_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_proc_sys_reset_1_0 || ORIG_REF_NAME==Arty_Z7_20_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_2_0/Arty_Z7_20_proc_sys_reset_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_proc_sys_reset_2_0 || ORIG_REF_NAME==Arty_Z7_20_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_processing_system7_0_0/Arty_Z7_20_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_processing_system7_0_0 || ORIG_REF_NAME==Arty_Z7_20_processing_system7_0_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_ps7_0_axi_periph_0/Arty_Z7_20_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_ps7_0_axi_periph_0 || ORIG_REF_NAME==Arty_Z7_20_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_rst_ps7_0_100M_0/Arty_Z7_20_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_rst_ps7_0_100M_0 || ORIG_REF_NAME==Arty_Z7_20_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_xlconcat_0_0/Arty_Z7_20_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_xlconcat_0_0 || ORIG_REF_NAME==Arty_Z7_20_xlconcat_0_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_xbar_0/Arty_Z7_20_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_xbar_0 || ORIG_REF_NAME==Arty_Z7_20_xbar_0} -quiet] -quiet

# IP: bd/Arty_Z7_20/ip/Arty_Z7_20_auto_pc_0/Arty_Z7_20_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_auto_pc_0 || ORIG_REF_NAME==Arty_Z7_20_auto_pc_0} -quiet] -quiet

# XDC: bd/Arty_Z7_20/Arty_Z7_20_ooc.xdc
