# This file was automatically generated by SDx
set vivado_error_file vivado_error.txt
set vivado_warn_file vivado_warning.txt

source ../../../.local/ocl_util.tcl
namespace import ocl_util::*

set _is_sdx_post_route_run false

